# Copyright 2018, OpenCensus Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: opencensus-pod-autoconf
  labels:
    app: opencensus-pod-autoconf
webhooks:
- name: pod-autoconf.opencensus.io 
  clientConfig:
    service:
      name: opencensus-pod-autoconf
      namespace: ${NAMESPACE} 
      path: "/autoconf"
    caBundle: ${CA_BUNDLE}
  # We are not doing anything security sensitive. In case our webhook has a bug
  # or is otherwise unavailable, it's better to keep operations going as usual.
  failurePolicy: Ignore
  # The sideEffects field is not available on older clusters.
  #sideEffects: None
  rules:
  # We only intercept pod creations. For other updates that might touch fields
  # we generally control, it is most likely for debugging purposes.
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
